### ISSUE TITLE
I'm having NullPointerException in your SKD

### ISSUE THREAD

**Issue by muhammadalkhalaf** [relateddigital/euromessage-android#4]
![image](https://user-images.githubusercontent.com/43862215/84163524-41821e80-aa7a-11ea-9aa4-9811eabb1ff9.png)

**Comment by relateddigital** [comment]
Hello Muhammad,

We could not repeat the same situation, there may be a problem with integration. Our support team will help you. If it is not solved, we can also set a developer meeting.

www.euromsg.com

**Comment by muhammadalkhalaf** [comment]
I added Euromessage to the dependencies in app/build.gradle
`implementation 'com.euromsg:euromsg:3.1.0'` 
then I added Service to Android Manifest file

then I added the following code to Main Activity :
```
       String userEmail = "";
        if (Hawk.get(USER_EMAIL) != null){
            userEmail = Hawk.get(USER_EMAIL);
        }
        EuroMobileManager euroMobileManager = EuroMobileManager.init("Secretcv", getContext());
        euroMobileManager.registerToFCM(getContext());
        euroMobileManager.setEmail(userEmail, getContext());
        euroMobileManager.setEuroUserId(userEmail, getContext());
        euroMobileManager.setAppVersion("3.3.14");
        euroMobileManager.setUserProperty("emailPermit","Y",getContext());
        euroMobileManager.setUserProperty("gsmPermit","Y",getContext());
        euroMobileManager.setUserProperty("pushPermit","Y",getContext());
        euroMobileManager.sync(getContext());
```

Why NullPointerException is thrown ?

**Comment by relateddigital** [comment]
Please Check your context which can be null, Also please make sure that, after generating a token from firebase, call the "sync" method.You may use FirebaseAuth library to make sure generating a token. It can be delay. You may also debug onNewToken method in EuroFirebaseMessagingService class.

**Comment by muhammadalkhalaf** [comment]
You can see the above image , context not null , getToken() return  null. 
I transferred the above code to onNewToken method , The problem was dissolved👍. But in my opinion you should mention to that in your documentation .

**Comment by muhammadalkhalaf** [comment]
The problem was not dissolved 👎  , onNewToken not calling but another way I got Token
 ```
FirebaseInstanceId.getInstance().getInstanceId()
                .addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
                    @Override
                    public void onComplete(@NonNull Task<InstanceIdResult> task) {
                        if (!task.isSuccessful()) {
                            Log.w(TAG, "getInstanceId failed", task.getException());
                            return;
                        }

                        // Get new Instance ID token
                        String token = task.getResult().getToken();
                        if (getContext() == null)return;
                        String userEmail = "";
                        if (Hawk.get(USER_EMAIL) != null){
                            userEmail = Hawk.get(USER_EMAIL);
                        }
                        EuroMobileManager euroMobileManager = SecretCvApplication.getEuroMobileManager();
                        euroMobileManager.registerToFCM(getContext());
                        euroMobileManager.setEmail(userEmail, getContext());
                        euroMobileManager.setEuroUserId(userEmail, getContext());
                        euroMobileManager.setAppVersion("3.3.14");
                        euroMobileManager.setUserProperty("emailPermit","Y",getContext());
                        euroMobileManager.setUserProperty("gsmPermit","Y",getContext());
                        euroMobileManager.setUserProperty("pushPermit","Y",getContext());
                        euroMobileManager.sync(getContext());
                    }
                });
 ```
Although Token not null , oldSubcription.getToken() return null .

**Comment by relateddigital** [comment]
Hello,

OnNewToken is called only when you open the application for the first time or when it is expired and the token is generated again.
The support team will open a request for a meeting with you.

Thank you.

**Comment by muhammadalkhalaf** [comment]
I called `FirebaseInstanceId.getInstance().getInstanceId() .... ` in Main Activity  . I get not null Token  but `oldSubcription.getToken()` in Your SDK return null

**Comment by muhammadalkhalaf** [comment]
how we can meet ?

**Comment by relateddigital** [comment]
Our support team will contact with SecretCV

Thank you.

**Comment by muhammadalkhalaf** [comment]
I used 3.0.9 version , That Exception isn't thrown because that if statement not exist
